apiVersion: airgapify.pecke.tt/v1alpha1
kind: Config
metadata:
  name: airgapify-config
spec:
  rules:
  - apiVersion: ceph.rook.io/v1
    kind: CephCluster
    paths:
    - "$.spec.cephVersion.image"
  - apiVersion: dex.gpu-ninja.com/v1alpha1
    kind: DexIdentityProvider
    paths:
    - "$.spec.image"
  - apiVersion: ldap.gpu-ninja.com/v1alpha1
    kind: LDAPDirectory
    paths:
    - "$.spec.image"
