name: Build, Test, and Release

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.14

    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Lint
      run: earthly +lint

    - name: Test
      run: |
        earthly +test
        earthly +integration-test
  
  release:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest

    steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - uses: earthly/actions-setup@v1
      with:
        version: v0.8.14

    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Build
      run: earthly +all --VERSION=${{ github.ref_name }}

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}