name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20.6'

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        skip-pkg-cache: true

    - name: Build
      run: make

    - name: Run Tests
      run: make test
  
  push:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '^1.20.6'

    - name: Build
      run: |
        mkdir -p bin
        cp LICENSE bin/LICENSE

        export GOOS=linux GOARCH=amd64
        make
        tar --zstd -cf dist/airgapify-${GOOS}-${GOARCH}.tar.zst -C bin LICENSE airgapify
        
        export GOOS=linux GOARCH=arm64
        make
        tar --zstd -cf dist/airgapify-${GOOS}-${GOARCH}.tar.zst -C bin LICENSE airgapify
        
        export GOOS=darwin GOARCH=amd64
        make
        tar --zstd -cf dist/airgapify-${GOOS}-${GOARCH}.tar.zst -C bin LICENSE airgapify
        
        export GOOS=darwin GOARCH=arm64
        make
        tar --zstd -cf dist/airgapify-${GOOS}-${GOARCH}.tar.zst -C bin LICENSE airgapify

        (cd dist; find . -type f -exec sha256sum {} \; >> ../checksums.txt)

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          checksums.txt
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}