name: Build and Test

on:
  push:
    branches: [ main ]
    tags: [ v* ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.15

    - name: Check Out Repo
      uses: actions/checkout@v3

    - name: Lint
      run: earthly +lint

    - name: Build
      run: earthly +airgapify

    - name: Test
      run: earthly +test
  
  push:
    needs: build-and-test
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: self-hosted

    steps:
    - uses: earthly/actions-setup@v1
      with:
        version: v0.7.15

    - name: Build
      run: earthly +all

    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          dist/*
          checksums.txt
          LICENSE
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}